const ERKM = {
  data: {
    jumlahSekolahRendah: 3,
    jumlahSekolahMenengah: 3,
    sekolahRendah: [
      {
        id: 1,
        nama: 'sekolah rendah alor janggus',
        negeri: 'kedah',
        daerah: 'kota setar',
        kodSekolah: 'YEE7872',
        enrolmen: '10',
        kelas: [
          {
            id: 1,
            nama: '1 adil',
            jumlahPelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'abu bakar as-siddiq',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'umar ibn khattab',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'usman ibn affan',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'ali ibn abi talib',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'thalhah ibn ubaidillah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
          {
            id: 2,
            nama: '1 amanah',
            jumlahPelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'abu darda',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'waraqah ibn naufal',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'bara bin azib',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'abdullah ibn rawahah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'usaid ibn hudayr',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
      {
        id: 2,
        nama: 'sekolah rendah tepi sungai',
        negeri: 'johor',
        daerah: 'batu pahat',
        kodSekolah: 'YEE7873',
        enrolmen: '5',
        kelas: [
          {
            id: 1,
            nama: '1A',
            jumlahPelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'zubayr ibn awwam',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'said ibn zayd',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'saad ibn abi waqqas',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'abdul rahman ibn auf',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'abu ubaidah ibn amir al jarrah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
      {
        id: 3,
        nama: 'sekolah rendah tepi sungai',
        negeri: 'selangor',
        daerah: 'hulu selangor',
        kodSekolah: 'YEE7874',
        enrolmen: '5',
        kelas: [
          {
            id: 1,
            nama: '1 bittikhun',
            jumlahPelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'zubayr ibn awwam',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'said ibn zayd',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'saad ibn abi waqqas',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'abdul rahman ibn auf',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'abu ubaidah ibn amir al jarrah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
    ],
    sekolahMenengah: [
      {
        id: 1,
        nama: 'sekolah menengah alor janggus',
        negeri: 'kedah',
        daerah: 'kota setar',
        kodSekolah: 'YEE7875',
        pelajar: '5',
        kelas: [
          {
            id: 1,
            nama: '1 amanah',
            jumlahPelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'abdullah ibn abbas',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'abdullah ibn umar',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'abdullah ibn zubayr',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'jafar ibn abi talib',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'zaid ibn harisah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
      {
        id: 2,
        nama: 'sekolah menengah air terjun',
        negeri: 'johor',
        daerah: 'batu pahat',
        kodSekolah: 'YEE7876',
        pelajar: '5',
        kelas: [
          {
            id: 1,
            nama: '1B',
            jumlahpelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'abdurrahman ibn sakhr',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'uthman ibn amir',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'abu sufyan ibn harb',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'muawiyah ibn abi sufyan',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'yazid ibn abi sufyan',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
      {
        id: 3,
        nama: 'sekolah menengah air terjun',
        negeri: 'selangor',
        daerah: 'hulu selangor',
        kodSekolah: 'YEE7877',
        pelajar: '5',
        kelas: [
          {
            id: 1,
            nama: '1 burtuqolun',
            jumlahpelajar: '5',
            pelajar: [
              {
                id: 1,
                nama: 'amir ibn fuhairah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 2,
                nama: 'bilal ibn rabah',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 3,
                nama: 'ammar ibn yasir',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 4,
                nama: 'huzaifah ibn yaman',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
              {
                id: 5,
                nama: 'suhaib al-rumi',
                jantina: 'lelaki',
                umur: '7',
                ic: '150101056235',
                tarikhLahir: '01-01-2015',
                jenisEtnik: 'melayu',
              },
            ],
          },
        ],
      },
    ],
  },
};

module.exports = ERKM;
